spring:
    redis:
        # 超时时间
        timeout: 10000ms
        # 服务器地址
        host: 192.168.159.128
        # 服务器端口，默认6379
        port: 6379
        # 数据库，默认0
        database: 0
        # 密码
        password: root
        lettuce:
            pool:
                #最大连接数，默认8
                max-active: 1024
                #最大连接阻塞等待时间，默认-1
                max-wait: 10000ms
                #最大空闲连接，默认8
                max-idle: 200
                #最小空闲连接，默认0
                min-idle: 5

    # thymeleaf ??
    thymeleaf:
      # ???? ?????????????false????????????????????true???????
        cache:false
    # ?????
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123
        hikari:
            # ????
            pool-name: DateHikariCP
            # ???????
            minimum-idle: 5
            # ?????????????600000 ?10???
            idle-timeout: 1800000
            # ????????10
            maximum-pool-size: 10
            # ?????????????
            auto-commit: true
            # ?????????0?????????30??
            max-lifetime: 1800000
            # ?????????30s
            connection-timeout: 30000
            # ?????????????
            connection-test-query: SELECT 1

mybatis-plus:
    # ?? Mapper.xml
    mapper-locations: classpath*:/mapper/*Mapper.xml
    # ?? MyBatis?????????????????
    type-aliases-package: com.xxxx.seckill.pojo

# MyBatis SQL?????????????? Mapper.xml ?????
logging:
    level:
        com.example.seckill.mapper: debug
